name: Deploy Helm Chart to EKS

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1   

    - name: Update kubeconfig for EKS cluster
      run: |
        aws eks update-kubeconfig --name your-cluster-name --region us-east-1

    - name: Install Helm chart from .tgz
      run: |
        helm upgrade --install my-app ./flask-app-0.1.0.tgz \
          --namespace default \
          --create-namespace
